### ISSUE TITLE
jsファイルを作成

### ISSUE THREAD

**Issue by GS-01-13-KuribayashiTsuzuki** [GS-01-13-KuribayashiTsuzuki/team_dev#1]
@gsactk 
jsファイルを作成してください。

**Comment by gsactk** [comment]
@GS-01-13-KuribayashiTsuzuki 
承知しました。

**Comment by gsactk** [comment]
@GS-01-13-KuribayashiTsuzuki 
js/main.jsを作成いたしました。
0631afd4c3f016e7cefef811cb75e542467ac1a9

**Comment by GS-01-13-KuribayashiTsuzuki** [comment]
@gsactk 
確認しました。ありがとう。
